# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d35705969e8ddd053c44969eee3cdca97ff22bcf58e550b6979f57b5b9b4daf0e2b93165d6c437dd7926bc025f0f8d547736d84eeaad4946459ed3ea44b3cf5

test:
  secret_key_base: 832def4f22c7d850b970cded7f0ce5770eecbfd713fdc32e2e0c3f347bf9b088b2c873a1e48711997e0e1cf3428d5b866ea28eca5d852d11742678c202a536a5

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
